kpi_structure = \
{   '지역전략산업 연계 특성화': {   'G-10 지역전략산업 특성화 대학 육성': [   {   'name': '지역 소재기업 취업률 실적',
                                                          'unit': '건',
                                                          'format': '%d',
                                                          'default_chart_type': 'bar',
                                                          'label_tag': '프로젝트',
                                                          'step': 1},
                                                      {   'name': '지역 주력산업분야 인력양성 실적 향상률',
                                                          'unit': '%',
                                                          'format': '%.1f',
                                                          'default_chart_type': 'line',
                                                          'label_tag': '프로젝트',
                                                          'step': 0.1},
                                                      {   'name': '현장형 수요 맞춤형 교육과정 참여실적',
                                                          'unit': '%',
                                                          'format': '%.1f',
                                                          'default_chart_type': 'line',
                                                          'label_tag': '프로젝트',
                                                          'step': 0.1},
                                                      {   'name': '지산학연 연구건수 및 연구비 규모(교수 1인당 연구건수)',
                                                          'unit': '건',
                                                          'format': '%d',
                                                          'default_chart_type': 'bar',
                                                          'label_tag': '대학',
                                                          'step': 1},
                                                      {   'name': '지산학연 연구건수 및 연구비 규모(교수 1인당 연구비)',
                                                          'unit': '천원',
                                                          'format': '%d',
                                                          'default_chart_type': 'bar_line',
                                                          'label_tag': '대학',
                                                          'step': 1000},
                                                      {   'name': '지산학연 연구 기술이전 실적(건당 수입료)',
                                                          'unit': '천원',
                                                          'format': '%d',
                                                          'default_chart_type': 'bar_line',
                                                          'label_tag': '대학',
                                                          'step': 1000}],
                         '산학연계 중점대학 육성 (연구개발, 인력양성, 산학협력)': {   '대학의 산학친화적 프로그램 운영': [   {   'name': '지역 소재기업 취업률 실적',
                                                                                             'unit': '건',
                                                                                             'format': '%d',
                                                                                             'default_chart_type': 'bar',
                                                                                             'label_tag': '프로젝트',
                                                                                             'step': 1},
                                                                                         {   'name': '현장형 수요 맞춤형 교육과정 '
                                                                                                     '참여실적',
                                                                                             'unit': '%',
                                                                                             'format': '%.1f',
                                                                                             'default_chart_type': 'line',
                                                                                             'label_tag': '프로젝트',
                                                                                             'step': 0.1},
                                                                                         {   'name': '지산학연 연구건수 및 연구비 '
                                                                                                     '규모(교수 1인당 연구건수)',
                                                                                             'unit': '건',
                                                                                             'format': '%d',
                                                                                             'default_chart_type': 'bar',
                                                                                             'label_tag': '대학',
                                                                                             'step': 1},
                                                                                         {   'name': '지산학연 연구건수 및 연구비 '
                                                                                                     '규모(교수 1인당 연구비)',
                                                                                             'unit': '천원',
                                                                                             'format': '%d',
                                                                                             'default_chart_type': 'bar_line',
                                                                                             'label_tag': '대학',
                                                                                             'step': 1000},
                                                                                         {   'name': '지산학연 연구 기술이전 '
                                                                                                     '실적(건당 수입료)',
                                                                                             'unit': '천원',
                                                                                             'format': '%d',
                                                                                             'default_chart_type': 'bar_line',
                                                                                             'label_tag': '대학',
                                                                                             'step': 1000}],
                                                                '취업역량 강화 프로그램': [   {   'name': '현장형 수요 맞춤형 교육과정 참여실적',
                                                                                        'unit': '%',
                                                                                        'format': '%.1f',
                                                                                        'default_chart_type': 'line',
                                                                                        'label_tag': '프로젝트',
                                                                                        'step': 0.1},
                                                                                    {   'name': '취업역량 강화 프로그램 참여학생 수',
                                                                                        'unit': '명',
                                                                                        'format': '%d',
                                                                                        'default_chart_type': 'bar',
                                                                                        'label_tag': '프로젝트',
                                                                                        'step': 1},
                                                                                    {   'name': '취업 활성화를 위한 프로그램 운영 실적',
                                                                                        'unit': '건',
                                                                                        'format': '%d',
                                                                                        'default_chart_type': 'bar',
                                                                                        'label_tag': '프로젝트',
                                                                                        'step': 1}]},
                         '공유대학 2.0': [   {   'name': '지역 공유대학 교육과정 운영 실적',
                                             'unit': '건',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '대학',
                                             'step': 1},
                                         {   'name': '지역 공유대학 교육과정 참여 실적',
                                             'unit': '명',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '대학',
                                             'step': 1},
                                         {   'name': '공유대학 이수자 취업률',
                                             'unit': '%',
                                             'format': '%.1f',
                                             'default_chart_type': 'line',
                                             'label_tag': '대학',
                                             'step': 0.1}]},
    '지역 연구 특성화': {   '지역연구 중심대학 육성': [   {   'name': '협약기관 취업 연계 실적',
                                             'unit': '건',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '프로젝트',
                                             'step': 1},
                                         {   'name': '내.외부 우수인력의 유입.순환실적',
                                             'unit': '명',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '프로젝트',
                                             'step': 1},
                                         {   'name': '외부기관과의 협력연구 실적',
                                             'unit': '건',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '프로젝트',
                                             'step': 1},
                                         {   'name': '지산학연 연구 건수 및 연구비 규모(교수 1인당 연구 건수)',
                                             'unit': '건',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '대학',
                                             'step': 1},
                                         {   'name': '지산학연 연구 건수 및 연구비 규모(교수 1인당 연구비)',
                                             'unit': '천원',
                                             'format': '%d',
                                             'default_chart_type': 'bar_line',
                                             'label_tag': '대학',
                                             'step': 1000},
                                         {   'name': '지산학연 연구 기술이전 실적',
                                             'unit': '천원',
                                             'format': '%d',
                                             'default_chart_type': 'bar_line',
                                             'label_tag': '대학',
                                             'step': 1000},
                                         {   'name': '지산학연 연구.개발 지식재산권 실적',
                                             'unit': '건',
                                             'format': '%d',
                                             'default_chart_type': 'bar',
                                             'label_tag': '대학',
                                             'step': 1}],
                     '연구특화 워케이션 클러스터 조성(남해안)': [   {   'name': '협약기관 취업 연계 실적',
                                                       'unit': '건',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar',
                                                       'label_tag': '프로젝트',
                                                       'step': 1},
                                                   {   'name': '내.외부 우수인력의 유입.순환실적',
                                                       'unit': '명',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar',
                                                       'label_tag': '프로젝트',
                                                       'step': 1},
                                                   {   'name': '외부기관과의 협력연구 실적',
                                                       'unit': '건',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar',
                                                       'label_tag': '프로젝트',
                                                       'step': 1},
                                                   {   'name': '지산학연 연구 건수 및 연구비 규모(교수 1인당 연구 건수)',
                                                       'unit': '건',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar',
                                                       'label_tag': '대학',
                                                       'step': 1},
                                                   {   'name': '지산학연 연구 건수 및 연구비 규모(교수 1인당 연구비)',
                                                       'unit': '천원',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar_line',
                                                       'label_tag': '대학',
                                                       'step': 1000},
                                                   {   'name': '지산학연 연구 기술이전 실적',
                                                       'unit': '천원',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar_line',
                                                       'label_tag': '대학',
                                                       'step': 1000},
                                                   {   'name': '지산학연 연구.개발 지식재산권 실적',
                                                       'unit': '건',
                                                       'format': '%d',
                                                       'default_chart_type': 'bar',
                                                       'label_tag': '대학',
                                                       'step': 1}]},
    '평생교육 체계 마련': {   '평생교육 거점대학 육성(권역, 단일형)': {   '경남형 평생교육 공동교육과정 체계 운영': [   {   'name': '성인학습자 고등교육 참여실적',
                                                                                    'unit': '%',
                                                                                    'format': '%.1f',
                                                                                    'default_chart_type': 'line',
                                                                                    'label_tag': '대학',
                                                                                    'step': 0.1},
                                                                                {   'name': '성인친화적 교육과정 개발.운영 실적',
                                                                                    'unit': '%',
                                                                                    'format': '%.1f',
                                                                                    'default_chart_type': 'line',
                                                                                    'label_tag': '프로젝트',
                                                                                    'step': 0.1},
                                                                                {   'name': '성인친화적 교육과정을 통한 인력배출 실적',
                                                                                    'unit': '%',
                                                                                    'format': '%.1f',
                                                                                    'default_chart_type': 'line',
                                                                                    'label_tag': '프로젝트',
                                                                                    'step': 0.1},
                                                                                {   'name': '대학-지역 간 네트워크 구축 및 운영 실적',
                                                                                    'unit': '건',
                                                                                    'format': '%d',
                                                                                    'default_chart_type': 'bar',
                                                                                    'label_tag': '대학',
                                                                                    'step': 1},
                                                                                {   'name': '대학 간 네트워크 구축 및 운영 실적',
                                                                                    'unit': '건',
                                                                                    'format': '%d',
                                                                                    'default_chart_type': 'bar',
                                                                                    'label_tag': '대학',
                                                                                    'step': 1}]},
                      '고등직업교육 거점대학 육성(권역, 단일형)': {   '산업기능인력양성(전문대-시군)': [   {   'name': '거버넌스 구축.운영 추진율',
                                                                                 'unit': '%',
                                                                                 'format': '%.1f',
                                                                                 'default_chart_type': 'line',
                                                                                 'label_tag': '대학',
                                                                                 'step': 0.1},
                                                                             {   'name': '특화분야 연계 교육과정 개발.운영 성과',
                                                                                 'unit': '%',
                                                                                 'format': '%.1f',
                                                                                 'default_chart_type': 'line',
                                                                                 'label_tag': '프로젝트',
                                                                                 'step': 0.1},
                                                                             {   'name': '직업교육 심화과정 이수율',
                                                                                 'unit': '%',
                                                                                 'format': '%.1f',
                                                                                 'default_chart_type': 'line',
                                                                                 'label_tag': '프로젝트',
                                                                                 'step': 0.1},
                                                                             {   'name': '지역 소재기업 취업률 실적',
                                                                                 'unit': '건',
                                                                                 'format': '%d',
                                                                                 'default_chart_type': 'bar',
                                                                                 'label_tag': '프로젝트',
                                                                                 'step': 1}]},
                      '외국인 유학생 유치': {   '외국인 유학생 유치‧지역정주 원스톱 지원': [   {   'name': '외국인 유학생 유치 실적',
                                                                          'unit': '명',
                                                                          'format': '%d',
                                                                          'default_chart_type': 'bar',
                                                                          'label_tag': '프로젝트',
                                                                          'step': 1},
                                                                      {   'name': '외국인 유학생 취업.정주 실적',
                                                                          'unit': '%',
                                                                          'format': '%.1f',
                                                                          'default_chart_type': 'line',
                                                                          'label_tag': '프로젝트',
                                                                          'step': 0.1},
                                                                      {   'name': '산학협력 유학생 역량향상 실적',
                                                                          'unit': '%',
                                                                          'format': '%.1f',
                                                                          'default_chart_type': 'line',
                                                                          'label_tag': '프로젝트',
                                                                          'step': 0.1},
                                                                      {   'name': '외국인 유학생 취업지원 실적',
                                                                          'unit': '%',
                                                                          'format': '%.1f',
                                                                          'default_chart_type': 'line',
                                                                          'label_tag': '프로젝트',
                                                                          'step': 0.1}],
                                        '산업인력 공급형 외국인 유학생 지원': [   {   'name': '외국인 유학생 유치 실적',
                                                                       'unit': '명',
                                                                       'format': '%d',
                                                                       'default_chart_type': 'bar',
                                                                       'label_tag': '프로젝트',
                                                                       'step': 1},
                                                                   {   'name': '외국인 유학생 취업.정주 실적',
                                                                       'unit': '%',
                                                                       'format': '%.1f',
                                                                       'default_chart_type': 'line',
                                                                       'label_tag': '프로젝트',
                                                                       'step': 0.1},
                                                                   {   'name': '산학협력 유학생 역량향상 실적',
                                                                       'unit': '%',
                                                                       'format': '%.1f',
                                                                       'default_chart_type': 'line',
                                                                       'label_tag': '프로젝트',
                                                                       'step': 0.1},
                                                                   {   'name': '외국인 유학생 취업지원 실적',
                                                                       'unit': '%',
                                                                       'format': '%.1f',
                                                                       'default_chart_type': 'line',
                                                                       'label_tag': '프로젝트',
                                                                       'step': 0.1}]}},
    '5-창업 및 지역문제 해결': {   '창업교육 거점대학 육성': {   '산업인력 공급형 외국인 유학생 지원': [   {   'name': '학생 및 교원 창업실적(창업 건수)',
                                                                             'unit': '건',
                                                                             'format': '%d',
                                                                             'default_chart_type': 'bar',
                                                                             'label_tag': '대학',
                                                                             'step': 1},
                                                                         {   'name': '학생 및 교원 창업실적(창업기업 수익금)',
                                                                             'unit': '천원',
                                                                             'format': '%d',
                                                                             'default_chart_type': 'bar',
                                                                             'label_tag': '대학',
                                                                             'step': 1000},
                                                                         {   'name': '창업 학점 교류제 참여학생 수',
                                                                             'unit': '명',
                                                                             'format': '%d',
                                                                             'default_chart_type': 'bar',
                                                                             'label_tag': '대학',
                                                                             'step': 1},
                                                                         {   'name': '창업동아리 참여학생 수',
                                                                             'unit': '명',
                                                                             'format': '%d',
                                                                             'default_chart_type': 'bar',
                                                                             'label_tag': '프로젝트',
                                                                             'step': 1},
                                                                         {   'name': '대학 간 연계 협력 및 지역사회와의 네트워크 활성화',
                                                                             'unit': '건',
                                                                             'format': '%d',
                                                                             'default_chart_type': 'bar',
                                                                             'label_tag': '프로젝트',
                                                                             'step': 1}]},
                          '지역문제 해결 리빙랩 선도대학 육성': {   '시군 연계형 지역문제 해결사업': [   {   'name': '거버넌스 구축.운영 추진율',
                                                                                 'unit': '%',
                                                                                 'format': '%.1f',
                                                                                 'default_chart_type': 'line',
                                                                                 'label_tag': '대학',
                                                                                 'step': 0.1},
                                                                             {   'name': '대학-지역 간 네트워크 구축 및 운영 실적',
                                                                                 'unit': '건',
                                                                                 'format': '%d',
                                                                                 'default_chart_type': 'bar',
                                                                                 'label_tag': '대학',
                                                                                 'step': 1},
                                                                             {   'name': '대학-지역 간 프로그램 참여인원 수',
                                                                                 'unit': '명',
                                                                                 'format': '%d',
                                                                                 'default_chart_type': 'bar',
                                                                                 'label_tag': '프로젝트',
                                                                                 'step': 1}],
                                                     '기초학문 등 사회참여 리빙랩 분야': [   {   'name': '거버넌스 구축.운영 추진율',
                                                                                   'unit': '%',
                                                                                   'format': '%.1f',
                                                                                   'default_chart_type': 'line',
                                                                                   'label_tag': '대학',
                                                                                   'step': 0.1},
                                                                               {   'name': '대학-지역 간 네트워크 구축 및 운영 실적',
                                                                                   'unit': '건',
                                                                                   'format': '%d',
                                                                                   'default_chart_type': 'bar',
                                                                                   'label_tag': '대학',
                                                                                   'step': 1},
                                                                               {   'name': '대학-지역 간 프로그램 참여인원 수',
                                                                                   'unit': '명',
                                                                                   'format': '%d',
                                                                                   'default_chart_type': 'bar',
                                                                                   'label_tag': '프로젝트',
                                                                                   'step': 1}]}}}